### ISSUE TITLE
Node version issue with Keytar

### ISSUE THREAD

**Issue by bushan1891** [stanlemon/salesforce-explorer#1]
HI i really like this implementation and looking forward if you can let me know how to fix this node version issue.

here is the error 

App threw an error during load
Error: The module '/Users/bushan/development/learning/salesforce-explorer/node_modules/keytar/build/Release/keytar.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/bushan/development/learning/salesforce-explorer/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/Users/bushan/development/learning/salesforce-explorer/node_modules/keytar/lib/keytar.js:61:3)

<img width="586" alt="screen shot 2018-01-26 at 6 26 26 pm" src="https://user-images.githubusercontent.com/12143841/35467678-70a2df14-02c6-11e8-9dbc-f5a80fe64b45.png">

any help on this is really appreciated

**Comment by stanlemon** [comment]
Did you run `npm run rebuild`?  The error you're seeing usually crops up when rebuild has not been run, the reason is because the version of node you're using locally doesn't match up with the one bundled in electron and keytar is a native lib.  If you haven't run rebuild, give that a shot. If you did, let me know along with your node version please. Thanks!
